### ISSUE TITLE
I CANNOT MAKE A CONVERSATION

### ISSUE THREAD

**Issue by schulz89sp** [aaryankotharii/SwiftUI-ChatApp#1]
Hi, I can create the user and log in, in the view where I look for people to start a conversation, I can't find anyone.
I realized that the database on Firebase was not done ...
I find only the image in the storage and the user in the authentication tab ...
Maybe a prolemic of rules on Firebase?
Thank you.

**Comment by aaryankotharii** [comment]
Hey, I have downloaded this repository and verified for the same. New chats can be created and the application is fully functional. If this problem still persists , I'd suggest you to setup your own firebase project and link this application. Feel free to drop any other issues in the future!

**Comment by schulz89sp** [comment]
user state changed
2020-07-02 00:05:01.401582+0200 ChatApp[43185:755446] 6.27.0 - [Firebase/Database][I-RDB038012] Listener at /users failed: permission_denied
Error Domain=com.firebase Code=1 "Permission denied" UserInfo={NSLocalizedDescription=Permission denied}
2020-07-02 00:05:01.401803+0200 ChatApp[43185:755446] 6.27.0 - [Firebase/Database][I-RDB038012] Listener at /user-messages/v0tRnXDMFUPAWBLePxJ8B2amQby2 failed: permission_denied
2020-07-02 00:05:01.402124+0200 ChatApp[43185:755446] 6.27.0 - [Firebase/Database][I-RDB038012] setValue: or removeValue: at /users/v0tRnXDMFUPAWBLePxJ8B2amQby2 failed: permission_denied

**Comment by schulz89sp** [comment]
Clone the project, user create but database permission denied, can you help me?
Thank you.

**Comment by aaryankotharii** [comment]
The firebase project has expired. You must create your own project and link it to the application.

**Comment by schulz89sp** [comment]
I clone the project, open Firebase create the project, copy the bundle Identifier, download the googleService file and replace it within the app, enable login with email and password, start the storage and the database firestore, then update the Pods, I launch the app and create the user, but the database does not update, while Storage does, where could I go wrong?
Thank you.
